package dorkbox;

import com.badlogic.gdx.ApplicationListener;
import com.badlogic.gdx.backends.gwt.GwtApplication;
import com.badlogic.gdx.backends.gwt.GwtApplicationConfiguration;

import dorkbox.demo.App;

public
class LibGdxHtmlDemo extends GwtApplication {

    @Override
    public
    GwtApplicationConfiguration getConfig() {
        return new GwtApplicationConfiguration(800, 580);
    }

    @Override
    public
    ApplicationListener createApplicationListener() {
        return new App();
    }
}
